# Generated by Django 5.0.3 on 2024-03-18 19:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaspublicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=31983)),
                ('cod_entidade', models.BigIntegerField(blank=True, null=True)),
                ('nome_escola', models.CharField(blank=True, max_length=254, null=True)),
                ('cod_ra', models.IntegerField(blank=True, null=True)),
                ('cod_dre', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'camadas.feature_point_escola_publica',
                'managed': False,
            },
        ),
    ]
