# Generated by Django 5.0.3 on 2024-03-18 23:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiaoadministrativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=31983)),
                ('ra_cira', models.IntegerField(blank=True, null=True)),
                ('ra_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('ra_codigo', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'camadas.feature_polygon_regioes_administrativas',
                'managed': False,
            },
        ),
    ]
