# Generated by Django 5.0.3 on 2024-03-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0003_loteexistente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='escolaspublicas',
            table='"camadas"."feature_point_escola_publica"',
        ),
        migrations.AlterModelTable(
            name='loteexistente',
            table='"camadas"."feature_polygon_lote_existente"',
        ),
        migrations.AlterModelTable(
            name='regiaoadministrativa',
            table='"camadas"."feature_polygon_regioes_administrativas"',
        ),
    ]
