# Generated by Django 5.0.3 on 2024-05-02 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0004_alter_escolaspublicas_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hidrografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=31983)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"camadas"."feature_line_hidrografia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lagoslagoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=31983)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"camadas"."feature_polygon_lagos_lagoas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistemaferroviario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=31983)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('layer', models.BigIntegerField(blank=True, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': '"camadas"."feature_line_sistema_ferroviario"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistemaviario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=31983)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('oneway', models.CharField(blank=True, max_length=1, null=True)),
                ('maxspeed', models.IntegerField(blank=True, null=True)),
                ('layer', models.BigIntegerField(blank=True, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': '"camadas"."feature_line_sistema_viario"',
                'managed': False,
            },
        ),
    ]
