# Generated by Django 4.2.13 on 2024-06-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0006_solicitacaopopulacao_tiposolicitacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaopopulacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiposolicitacao',
            options={},
        ),
    ]
