# Generated by Django 4.2.13 on 2024-06-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0007_alter_solicitacaopopulacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaopopulacao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposolicitacao',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='solicitacaopopulacao',
            name='tipoSolicitacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_solicitacao', to='pi_webgis.tiposolicitacao'),
        ),
    ]
