# Generated by Django 4.2.13 on 2024-06-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0008_alter_solicitacaopopulacao_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitacaoPopulacao',
        ),
    ]
